events {}

http {
    resolver 127.0.0.11 valid=30s;

    server {
        listen 80;
        client_max_body_size 50M;

        location /template/ {
            set $upstream template_ms;
            rewrite ^/template/(.*) /$1 break;
            proxy_pass http://$upstream:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Authorization $http_authorization;
        }

        location /auth/ {
            set $upstream auth_ms;
            rewrite ^/auth/(.*) /$1 break;
            proxy_pass http://$upstream:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Authorization $http_authorization;
        }

        location /users/ {
            set $upstream users_ms;
            rewrite ^/users/(.*) /$1 break;
            proxy_pass http://$upstream:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Authorization $http_authorization;
        }

        location /documents/ {
            set $upstream documents_ms;
            rewrite ^/documents/(.*) /$1 break;
            proxy_pass http://$upstream:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Authorization $http_authorization;
        }

        location /products/ {
            set $upstream products_ms;
            rewrite ^/products/(.*) /$1 break;
            proxy_pass http://$upstream:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /payments/ {
            set $upstream payments_ms;
            rewrite ^/payments/(.*) /$1 break;
            proxy_pass http://$upstream:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Authorization $http_authorization;
        }

        location /activities/ {
            set $upstream activities_ms;
            rewrite ^/activities/(.*) /$1 break;
            proxy_pass http://$upstream:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Authorization $http_authorization;
        }
    }
}
